Id: 72092e64-842e-4bf3-8916-dacd940b21cc
Author: R-Koubou
ManufacturerName: IK Multimedia
ProductName: MODO Bass 2
PatchName: Default
Description: IK Multimedia MODO Bass 2 - Default
Articulations:
  - Name: Idle
    MidiMessages: []
  - Name: Pizzicato / Finger
    MidiMessages:
      - Status: 144
        Data1: 25
        Data2: 100
  - Name: Pick
    MidiMessages:
      - Status: 144
        Data1: 27
        Data2: 100
  - Name: Slap
    MidiMessages:
      - Status: 144
        Data1: 30
        Data2: 100
  - Name: Ham. On/Pull Off
    MidiMessages:
      - Status: 144
        Data1: 24
        Data2: 100
  - Name: Ghost Mode
    MidiMessages:
      - Status: 144
        Data1: 21
        Data2: 100
  - Name: Harmonics
    MidiMessages:
      - Status: 144
        Data1: 29
        Data2: 100
  - Name: Index/Down Stroke | Force Slap
    MidiMessages:
      - Status: 144
        Data1: 13
        Data2: 100
  - Name: Middle/Down Stroke | Force Pull
    MidiMessages:
      - Status: 144
        Data1: 15
        Data2: 100
  - Name: Force C String
    MidiMessages:
      - Status: 144
        Data1: 12
        Data2: 100
  - Name: Force G String
    MidiMessages:
      - Status: 144
        Data1: 31
        Data2: 100
  - Name: Force D String
    MidiMessages:
      - Status: 144
        Data1: 26
        Data2: 100
  - Name: Force A String
    MidiMessages:
      - Status: 144
        Data1: 21
        Data2: 100
  - Name: Force E String
    MidiMessages:
      - Status: 144
        Data1: 28
        Data2: 100
  - Name: Force B String
    MidiMessages:
      - Status: 144
        Data1: 23
        Data2: 100
  - Name: Stop On Detach
    MidiMessages:
      - Status: 144
        Data1: 32
        Data2: 100
  - Name: DB Slap Noise
    MidiMessages:
      - Status: 144
        Data1: 37
        Data2: 100
  - Name: DB Stop Strings
    MidiMessages:
      - Status: 144
        Data1: 39
        Data2: 100
