name: Build SSG Page
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - develop
      - feature/**
      - fix/**
      - refactor/**

  workflow_call:
  workflow_dispatch:

jobs:
  build-ssg-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: 'Asia/Tokyo'
      ARTICLUSTER_INPUT: ${{ github.workspace }}/articluster-files
      ARTICLUSTER_OUTPUT: ${{ github.workspace }}/zensical/docs/assets/converted
      ARTICLUSTER_MARKDOWN_OUTPUT: ${{ github.workspace }}/zensical/docs

    steps:
      #----------------------------------------------------------
      # Checkout repository
      #----------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      #----------------------------------------------------------
      # Setup .NET SDK
      #----------------------------------------------------------
      - name: Install .NET SDK
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ vars.DOTNET_SDK_VERSION }}

      #----------------------------------------------------------
      # Setup dependency build tools from .prototools
      #----------------------------------------------------------
      - name: Setup Dependency Build Tools from .prototools
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4
        with:
          auto-install: true

      #----------------------------------------------------------
      # Convert articluster-files/
      # Generate Markdown Page for zensical
      #----------------------------------------------------------
      - name: Convert Articluster-files and Generate Markdown Page for zensical
        run: |
          dotnet tool exec -y ArtiCluster@${{ vars.USE_ARTICLUSTER_VERSION }} \
              convert \
              --output-markdown-list-dir ${ARTICLUSTER_MARKDOWN_OUTPUT} \
              ${ARTICLUSTER_INPUT} \
              ${ARTICLUSTER_OUTPUT}

      #----------------------------------------------------------
      # Replace build information in zensical page
      #----------------------------------------------------------
      - name: Replace build information in zensical page (index.md)
        run: |
          BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%S+09:00")
          VERSION=${{ github.ref_name }}@${{ github.sha }}
          sed -i "s?##VERSION##?${VERSION}?g" zensical/docs/index.md
          sed -i "s?##BUILD_DATE##?${BUILD_DATE}?g" zensical/docs/index.md
          sed -i "s?##ARTICLUSTER_VERSION##?${{ vars.USE_ARTICLUSTER_VERSION }}?g" zensical/docs/index.md

          {
            echo "## Build Information";
            echo ""
            echo "|name|value|"
            echo "|----|-----|"
            echo "|Version|${VERSION}|"
            echo "|Build Date|${BUILD_DATE}|"
            echo "|ArtiCluster Version|${{ vars.USE_ARTICLUSTER_VERSION }}|"
          } >> $GITHUB_STEP_SUMMARY

      #----------------------------------------------------------
      # Build zensical page
      #----------------------------------------------------------
      - name: Build zensical page
        run: |
          pushd zensical
            uvx zensical build --clean
          popd

      #----------------------------------------------------------
      # Upload zensical page artifact
      #----------------------------------------------------------
      - name: Upload zensical page artifact
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: page-files
          path: zensical/site

      #----------------------------------------------------------
      # Upload ArtiCluster converted data artifact
      #----------------------------------------------------------
      - name: Upload ArtiCluster converted data artifact
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          name: all-converted-files
          path: ${{ env.ARTICLUSTER_OUTPUT }}
