name: Check YAML UUID Duplication

on:
  pull_request:

  push:
    branches:
      - develop
      - feature/**
      - fix/**
      - refactor/**

  workflow_call:
  workflow_dispatch:

jobs:
  check-yaml-uuid-duplication:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------------------
      # Checkout repository
      #----------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      #----------------------------------------------------------
      # Setup dependency build tools from .prototools
      #----------------------------------------------------------
      - name: Setup Dependency Build Tools from .prototools
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4
        with:
          auto-install: true

      #----------------------------------------------------------
      # Check YAML UUID Duplication
      #----------------------------------------------------------
      - name: Check YAML UUID Duplication
        run: |
          pushd tools/check-uuid-duplication
            uv sync
            uv run python main.py ../../articluster-files
          popd
